#!/usr/bin/env bash
# scripts/emit_tasks.sh
#
# For each benchmark listed below, runs the DSWP task decomposition with
# post-DSWP lock synthesis and emits the task bodies.  Collects the output
# into reports/tasks_appendix.tex for inclusion in a paper appendix.
#
# Usage: bash scripts/emit_tasks.sh
# Usually invoked via:  make latex

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VCY="$REPO_ROOT/src/vcy.exe"
GC="$REPO_ROOT/benchmarks/global_commutativity"
OUT="$REPO_ROOT/reports/tasks_appendix.tex"

if [[ ! -x "$VCY" ]]; then
    echo "ERROR: $VCY not found. Run 'make' first." >&2
    exit 1
fi

mkdir -p "$REPO_ROOT/reports"
TASKS_DIR="$REPO_ROOT/reports/tasks"
mkdir -p "$TASKS_DIR"

# Temp files for file-based benchmarks; cleaned up on exit
TMPF=$(mktemp -d)
# simple-io hardcodes open_in "a.txt" relative to its working directory
SIMPLEIO_A="$REPO_ROOT/src/a.txt"
trap 'rm -rf "$TMPF"; rm -f "$SIMPLEIO_A"' EXIT

for letter in a b c d e f; do
    printf '%scontent\n' "$letter" > "$TMPF/${letter}.txt"
done
printf 'acontent\n' > "$SIMPLEIO_A"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# emit_tasks NAME FILE [ARGS...]
#   Run --dswp --synthesize-locks --emit-tasks and return output.
#   Returns empty string on timeout/error.
emit_tasks() {
    local name="$1" file="$2"; shift 2
    timeout 10 "$VCY" interp --dswp --synthesize-locks --emit-tasks \
        "$file" "$@" 2>/dev/null || true
}

# latex_escape TEXT
#   Escape characters that are special in a LaTeX verbatim context
#   (verbatim is already safe, but used for section/subsection text).
latex_escape() {
    printf '%s' "$1" \
        | sed 's/\\/\\textbackslash{}/g' \
        | sed 's/_/\\_/g' \
        | sed 's/\^/\\^{}/g' \
        | sed 's/&/\\&/g' \
        | sed 's/%/\\%/g' \
        | sed 's/\$/$\\$/g' \
        | sed 's/#/\\#/g' \
        | sed 's/{/\\{/g' \
        | sed 's/\\n/newline/g' \
        | sed 's/\n/newline/g' \
        | sed 's/}/\\}/g'
}

# append_benchmark NAME SLUG OUTPUT
#   Write the task output to reports/tasks/SLUG.txt, then append a
#   \lstinputlisting reference to the LaTeX file.  Using a file rather
#   than an inline heredoc avoids all bash string-expansion issues with
#   backslash sequences (e.g. \n inside VCY string literals).
append_benchmark() {
    local name="$1" slug="$2" output="$3"
    local txtfile="$TASKS_DIR/${slug}.txt"
    printf '%s\n' "$output" > "$txtfile"
    cat >> "$OUT" << LATEXEOF

% ----- $(printf '%s' "$name" | tr '[:lower:]' '[:upper:]') -----
\subsection{Benchmark \texttt{$(latex_escape "$name")}}

\lstinputlisting[style=vcytasks]{tasks/${slug}.txt}

LATEXEOF
}

# ---------------------------------------------------------------------------
# LaTeX file header
# ---------------------------------------------------------------------------
cat > "$OUT" << 'HEADER'
% Auto-generated by scripts/emit_tasks.sh — do not edit by hand.
%
% Include in a paper with:
%   \usepackage{listings}
%   \graphicspath{{reports/}}   % so \lstinputlisting finds reports/tasks/
%   \input{reports/tasks_appendix}
%
% Or compile standalone from the reports/ directory:
%   cd reports && pdflatex tasks_appendix_standalone.tex
%
% Task body files are in reports/tasks/*.txt and are included via
% \lstinputlisting, which reads bytes directly and avoids all shell
% string-expansion issues with escape sequences (e.g. \n in VCY strings).

% Required in the including document:
%   \usepackage{listings}
%   \usepackage{xcolor}

\lstdefinestyle{vcytasks}{
  basicstyle=\footnotesize\ttfamily,
  breaklines=true,
  breakatwhitespace=false,
  keepspaces=true,
  columns=flexible,
  frame=single,
  framesep=4pt,
  xleftmargin=8pt,
  xrightmargin=4pt,
  aboveskip=4pt,
  belowskip=4pt,
  showstringspaces=false,
  commentstyle=\color{gray},
  keywordstyle=\bfseries,
  morekeywords={while,if,else,int,return,bool,true,false,
                mutex_lock,mutex_unlock,SendDep,SendEOP},
}

HEADER

# ---------------------------------------------------------------------------
# Benchmarks
# ---------------------------------------------------------------------------

echo "Emitting tasks for:"

echo -n "  ps-dswp-ek ... "
output=$(emit_tasks "ps-dswp-ek" "$GC/ps-dswp-ek.vcy" 1 1)
append_benchmark "ps-dswp-ek" "ps-dswp-ek" "$output"
echo "done"

echo -n "  commset (md5) ... "
output=$(emit_tasks "commset" "$GC/commset.vcy" \
    "$TMPF/a.txt" "$TMPF/b.txt" "$TMPF/c.txt" "$TMPF/d.txt")
append_benchmark "commset (md5)" "commset-md5" "$output"
echo "done"

echo -n "  commset-kmeans ... "
output=$(emit_tasks "commset-kmeans" "$GC/commset-kmeans.vcy" 1)
append_benchmark "commset-kmeans" "commset-kmeans" "$output"
echo "done"

echo -n "  commset-potrace ... "
output=$(emit_tasks "commset-potrace" "$GC/commset-potrace.vcy" \
    1 "$TMPF/a.txt" "$TMPF/b.txt" "$TMPF/c.txt" \
      "$TMPF/d.txt" "$TMPF/e.txt" "$TMPF/f.txt")
append_benchmark "commset-potrace" "commset-potrace" "$output"
echo "done"

echo -n "  motivation ... "
output=$(emit_tasks "motivation" "$GC/motivation.vcy" 100 10)
append_benchmark "motivation" "motivation" "$output"
echo "done"

echo -n "  simple-io ... "
output=$(emit_tasks "simple-io" "$GC/simple-io.vcy" \
    "$TMPF/a.txt" "$TMPF/b.txt" "$TMPF/c.txt" "$TMPF/d.txt")
append_benchmark "simple-io" "simple-io" "$output"
echo "done"

echo -n "  multi-blocks ... "
output=$(emit_tasks "multi-blocks" "$GC/multi-blocks.vcy" 1)
append_benchmark "multi-blocks" "multi-blocks" "$output"
echo "done"

echo -n "  vote-run ... "
output=$(emit_tasks "vote-run" "$GC/vote-run.vcy" 1)
append_benchmark "vote" "vote" "$output"
echo "done"

echo -n "  blockchain-erc20 ... "
output=$(emit_tasks "blockchain-erc20" "$GC/blockchain-erc20-1dArray.vcy" 1 1 2)
append_benchmark "blockchain-erc20" "blockchain-erc20" "$output"
echo "done"

echo -n "  banking ... "
output=$(emit_tasks "banking" "$GC/banking.vcy" 1 100 1000)
append_benchmark "banking" "banking" "$output"
echo "done"

echo ""
echo "Written: $OUT"
