(include_subdirs unqualified)

(library
 (name vcy)
 (public_name vcy)
 (libraries unix threads str servois2
            (select parallel.ml from
             (domainslib -> parallel/parallel.multicore.ml)
             (-> parallel/parallel.singlecore.ml)))
 (modules (:standard \ run))
 (wrapped true)
 (library_flags -linkall)
 (synopsis "Veracity language"))

(executable
 (name run)
 (public_name vcyrun)
 (modules run)
 (libraries vcy)
 (promote (until-clean)))

(env
 (dev
  (flags (:standard -warn-error -A -w -27-33 -w -32 ))))
